# Generated by Django 5.1.4 on 2025-06-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='0755913939', max_length=20)),
                ('recipient_name', models.CharField(default='MARTIN MUNGAI', max_length=100)),
            ],
            options={
                'verbose_name': 'Payment Information',
                'verbose_name_plural': 'Payment Information',
            },
        ),
    ]
