# Generated by Django 5.1.4 on 2025-06-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='paybill_number',
            field=models.CharField(default='303030', max_length=20),
        ),
    ]
