# Generated by Django 5.1.4 on 2025-05-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hall6_side',
            field=models.CharField(blank=True, choices=[('A', 'Side A'), ('B', 'Side B')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='hall',
            field=models.CharField(choices=[('Hall 1', 'Hall 1'), ('Hall 2', 'Hall 2'), ('Hall 3', 'Hall 3'), ('Hall 4', 'Hall 4'), ('Hall 5', 'Hall 5'), ('Hall 6', 'Hall 6')], max_length=20),
        ),
    ]
