# Generated by Django 5.1.4 on 2025-05-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_hall6_side_alter_room_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(),
        ),
    ]
